version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    cooldown:
      min-release-age: "3 days"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 0
    cooldown:
      min-release-age: "3 days"
