import type kdbx from '@/lib/kdbx.lib';
import type { IconSvgElement } from '@hugeicons/react';
import {
  Key01Icon,
  Globe02Icon,
  Alert01Icon,
  ServerStack01Icon,
  Pin02Icon,
  Comment01Icon,
  PuzzleIcon,
  StickyNote01Icon,
  PlugSocketIcon,
  IdentityCardIcon,
  Attachment01Icon,
  Camera01Icon,
  Wifi01Icon,
  Link01Icon,
  BatteryCharging01Icon,
  BarcodeIcon,
  LocationStar01Icon,
  CdIcon,
  ComputerIcon,
  Mail01Icon,
  Settings01Icon,
  ClipboardCheckIcon,
  FileAddIcon,
  ModernTvIcon,
  BatteryEmptyIcon,
  InboxIcon,
  FloppyDiskIcon,
  HardDriveIcon,
  FileQuestionMarkIcon,
  LockPasswordIcon,
  ComputerTerminal01Icon,
  PrinterIcon,
  WorkflowCircle01Icon,
  Flag01Icon,
  Wrench01Icon,
  LaptopIcon,
  Archive01Icon,
  CreditCardIcon,
  WindowsNewIcon,
  Clock01Icon,
  MailSearch01Icon,
  Flag02Icon,
  SdCardIcon,
  Delete02Icon,
  NoteIcon,
  CalendarRemove01Icon,
  InformationCircleIcon,
  PackageIcon,
  Folder01Icon,
  FolderOpenIcon,
  PackageOpenIcon,
  SquareUnlock01Icon,
  FileLockIcon,
  CheckmarkCircle01Icon,
  PencilEdit01Icon,
  Image01Icon,
  AddressBookIcon,
  ListViewIcon,
  UserLock01Icon,
  ToolboxIcon,
  Home01Icon,
  StarIcon,
  Robot01Icon,
  FeatherIcon,
  Apple01Icon,
  WikipediaIcon,
  MoneyBag01Icon,
  Certificate01Icon,
  SmartPhone01Icon,
} from '@hugeicons/core-free-icons';

// index matches kdbx's standard KeePass icon set (0-68), mapped to the closest available Hugeicons equivalent
export const STANDARD_ICON_MAP: IconSvgElement[] = [
  Key01Icon,
  Globe02Icon,
  Alert01Icon,
  ServerStack01Icon,
  Pin02Icon,
  Comment01Icon,
  PuzzleIcon,
  StickyNote01Icon,
  PlugSocketIcon,
  IdentityCardIcon,
  Attachment01Icon,
  Camera01Icon,
  Wifi01Icon,
  Link01Icon,
  BatteryCharging01Icon,
  BarcodeIcon,
  LocationStar01Icon,
  CdIcon,
  ComputerIcon,
  Mail01Icon,
  Settings01Icon,
  ClipboardCheckIcon,
  FileAddIcon,
  ModernTvIcon,
  BatteryEmptyIcon,
  InboxIcon,
  FloppyDiskIcon,
  HardDriveIcon,
  FileQuestionMarkIcon,
  LockPasswordIcon,
  ComputerTerminal01Icon,
  PrinterIcon,
  WorkflowCircle01Icon,
  Flag01Icon,
  Wrench01Icon,
  LaptopIcon,
  Archive01Icon,
  CreditCardIcon,
  WindowsNewIcon,
  Clock01Icon,
  MailSearch01Icon,
  Flag02Icon,
  SdCardIcon,
  Delete02Icon,
  NoteIcon,
  CalendarRemove01Icon,
  InformationCircleIcon,
  PackageIcon,
  Folder01Icon,
  FolderOpenIcon,
  PackageOpenIcon,
  SquareUnlock01Icon,
  FileLockIcon,
  CheckmarkCircle01Icon,
  PencilEdit01Icon,
  Image01Icon,
  AddressBookIcon,
  ListViewIcon,
  UserLock01Icon,
  ToolboxIcon,
  Home01Icon,
  StarIcon,
  Robot01Icon,
  FeatherIcon,
  Apple01Icon,
  WikipediaIcon,
  MoneyBag01Icon,
  Certificate01Icon,
  SmartPhone01Icon,
];

// standard KeePass icon indices used as fallbacks when an entry/group has no icon set
const KEY_ICON_INDEX = 0;
const FOLDER_ICON_INDEX = 48;

export const DEFAULT_ICON = STANDARD_ICON_MAP[KEY_ICON_INDEX];

export const getEntryIcon = (entry: kdbx.KdbxEntry): number => entry.icon ?? KEY_ICON_INDEX;

export const getGroupIcon = (group: kdbx.KdbxGroup): number => group.icon ?? FOLDER_ICON_INDEX;

export const resolveStandardIcon = (index: number): IconSvgElement => STANDARD_ICON_MAP[index] ?? DEFAULT_ICON;
